boostcampwm2023/iOS03-TravelShare

iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIColor+.swift
iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIImage+.swift

- #10 
- Asset 추가
- 색상과 폰트 처럼 이미지도 디자인 시스템에 추가하기로 결정해서 작업하였습니다.

[add][#10] DesignSystem color, image Asset 추가

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Common/TabBar/Model/TabComponent.swift
iOS/Macro/Macro/Common/TabBar/Model/TabLocation.swift
iOS/Macro/Macro/Common/TabBar/View/TabBarBackgroundLargeCirclceView.swift
iOS/Macro/Macro/Common/TabBar/View/TabBarBackgroundSmallView.swift
iOS/Macro/Macro/Common/TabBar/View/TabBarCenterView.swift
iOS/Macro/Macro/Common/TabBar/View/TabBarOpacityView.swift
iOS/Macro/Macro/Common/TabBar/View/TabBarViewController.swift
iOS/Macro/Macro/Common/TabBar/View/TabComponentView.swift
iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
iOS/Macro/Macro/Util/CAGradientLayer+.swift
iOS/Macro/Macro/Util/CircularViewProtocol.swift
iOS/Macro/Macro/Util/UIScreen+.swift

- #15 
- Custom Tabbar UI 및 로직 작업
- home VC에 넣어서 테스트 가능합니다 :)
```swift
let tabVM = TabBarViewModel()
let tabVC = TabbarViewController(viewModel: tabVM)
self.view.addSubview(tabVC.view)
```
- Custom Tabbar를 구현하였습니다. 
combine을 사용한 게 처음이라 아직 이해하지 못하고 썼어요. 제대로 쓴 게 맞을까요? CurrentValueSubject가 초기값을 갖는 Publisher라서 인터넷의 블로그를 보고 사용하긴 했는 데 아직 전혀 감을 못잡고 있습니다.
MVVM 을 사용하기로 했는 데, 구현에 급급해서 적용하지 못했습니다. ComponetTabView가 정보를 갖고 있어서 떼어 내야 합니다.
뿐만 아니라 layout을 잡을 때, Life Cycle의 이해 부족 + 구현 실력 부족 으로 인해 코드가 엉망이 되었습니다.
특히. setNeedsLayout() 에서 기존의 subview를 제거하고 다시 setUp하도록 구현해놔서 리팩토링이 필수입니다.
강한 순환 참조가 생길 만한 요소가 많습니다. 죄송합니다.
11월 15일, 경호님, 나훈님과 뷰모델에 input, output pattern을 적용하기로 했기에 차후 이 부분을 수정할 때 함께 고려하도록 하겠습니다.
아직 final과 접근 제어자, 상수, 변수 구분을 제대로 이해하고 활용 및 적용하지 못하고 있습니다. 전체적인 리팩토링이 필요합니다.
15Pro …

[feat][#15] Custom tabbar 구현

---

server/.eslintrc.js
server/src/map/map.kakao.controller.ts
server/src/map/map.kakao.search.response.dto.ts
server/src/map/map.kakao.service.ts
server/src/map/map.module.ts

[Add] merge Improve/kakaomap to Dev

---

server/API_GUIDE.md
server/src/auth/apple/apple.auth.controller.ts
server/src/map/map.controller.ts
server/src/map/map.kakao.controller.ts
server/src/map/map.module.ts
server/src/post/post.controller.ts
server/src/user/user.controller.ts

- #39 
- Api 구현 현황과 대략적인 흐름을 작성하였습니다.
- Swagger 문서에서 형식적인 명세를 작성하였으나, 흐름적인 부분에 대해 설명이 미흡하여 추가 문서를 작성했습니다.
- 미구현 사항에 대해서도 한 눈에 파악할 수 있도록 작성하였습니다.
- 계속 추가하도록 하겠습니다.

[add] [#39] Api Guideline 작성

---

server/src/map/map.kakao.search.accuracy.query.dto.ts
server/src/map/map.kakao.search.distance.query.dto.ts

- #44 
- DTO 작성에서 validation 로직에 약간의 오류를 발견하고 수정하였습니다.
- 이상 동일
Close #44

[fix] [#44] validation 오류 수정

---

server/src/post/post.module.ts
server/src/user/user.controller.ts
server/src/user/user.module.ts
server/src/user/user.profile.query.dto.ts
server/src/user/user.service.ts

- #48 
- 유저 관련 Api를 작성하고 대충 실행 및 대충 테스트하여 작동은 하는 것 같아 일단 PR을 올립니다.
- /user 이하 api들을 작성했습니다.

[feat] [#48] User API 초안 작성

---

iOS/Macro/Macro/App/SceneDelegate.swift

#12 
앱 시작 시 Login 화면 연결
Test를 위해 Scene Delegate에서 Login 화면 연결로 고정

[chore][#12] SecneDeleaget Login 화면으로 연결 고정

---

server/src/auth/apple/apple.auth.controller.ts
server/src/auth/apple/apple.auth.service.ts

- #55 
- Apple 로그인 과정에서 발생한 오류를 수정했습니다.
- Jwt Sign 과정에서 plainObject가 아니면 sign을 할 수 없어 발생했던 오류를 수정했습니다.
Close #55

[fix] jwt sign 오류 수정

---

server/docker-compose.yaml
server/package.json
server/src/auth/apple/apple.auth.service.ts
server/src/config/app.config.ts
server/src/entities/post.entity.ts
server/src/entities/user.entity.ts
server/src/migrations/1700591341852-Migration.ts

- #60 
- 중복되어 로그인 시도 시 무조건 오류가 나는 문제를 해결했습니다.
- 회원 가입 과정에서 애플 로그인 테이블이 제대로 맵핑되지 않았었습니다.
close #60

[fix] [#60] apple auth 중복 유저 이슈 해결

---

.github/workflows/deploy.yaml

- #54 
- 배포 관련 몇 가지 수정, 오타 등을 고칩니다.
- 이상 동일

[correct] [#54] Update deploy.yaml

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/VIew/LocationInfoViewController.swift
iOS/Macro/Macro/Scene/Travel/Entities/LocationDetail.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift

locationInfo 에 대한 작업중 Search 기능이 수행이 안되는 버그를 찾음.
핵심 기능이므로 우선 merge 필요
Search기능이 수행이 안되는 것에 대해 버그 수정

[fix][#67] Search가 안되던 버그 수정

---

iOS/Macro/Macro/Common/TabBar/View/TabBarViewController.swift

- #70
-  tabbarViewController가 childViewController를 추가하도록 로직을 수정합니다.
- tabbarViewController가 childViewController를 추가하도록 로직을 수정합니다.

[feat][#70] navigation tab

---

server/package-lock.json
server/src/app.module.ts
server/src/auth/apple/apple.auth.controller.ts
server/src/auth/auth.controller.ts
server/src/file/file.constants.ts
server/src/file/file.controller.ts
server/src/file/file.module.ts
server/src/file/file.service.ts
server/src/file/s3.provider.factory.ts
server/src/main.ts
server/src/map/map.controller.ts
server/src/post/post.controller.ts
server/src/user/user.controller.ts
server/src/utils/rest.controller.decorator.ts
server/src/utils/utils.module.ts

- #65 
- 이미지 등 데이터를 업로드 하기 위해 raw data처리를 할 수 있도록 Object Storage와 연동을 하였습니다.
- Object Storage와 연동을 하고 이에 대해 간단히 API를 작성했습니다.
Stream으로 처리되지 않고, nest.js는 raw data를 다루기 적합하지 않은 것 같다.
Close #65

[add] [#65] Object Storage(S3) 셋팅 및 API 초안 작성

---

server/src/entities/post.entity.ts
server/src/migrations/1700669514013-Migration.ts
server/src/post/post.controller.ts
server/src/post/post.find.query.dto.ts
server/src/post/post.hist.query.dto.ts
server/src/post/post.pagenation.dto.ts
server/src/post/post.read.response.dto.ts
server/src/post/post.service.ts
server/src/post/post.write.body.ts
server/src/user/user.service.ts
server/src/utils/response.validation.interceptor.ts

- #54 
- 배포 이후 테스트를 하며 테이블과 로직을 간소화하고 보완했습니다.
- 일단 이제 배포를 자동화하여 비교적 꼬일 일은 적어졌다고 생각이 들지만,
코드가 많아지면서 커밋이 꼬여 분명 작업했던 내용도 어디로 사라져버리곤 한다...
- 분명 post 로직을 바꿔놨었는데 어디로 꼬여버렸는지 잘 못찾겠고,
그냥 다시 수정했다.
이제 정말 연동을 위한 준비를 거의 다 한 것 같다.
Close #54

[enhancement] [#54] 테이블 수정 및 로직 수정

---

server/src/entities/user.entity.ts
server/src/migrations/1700700853445-Migration.ts
server/src/post/post.controller.ts
server/src/post/post.detail.query.dto.ts
server/src/post/post.detail.response.dto.ts
server/src/post/post.find.response.dto.ts
server/src/post/post.pagenation.dto.ts
server/src/post/post.service.ts
server/src/utils/response.validation.interceptor.ts

- #77 
- 게시글 api 개선작업을 했습니다.
- 오류 수정 및 로직 개선 작업을 진행했습니다.
- 전반적인 컨벤션이 달라져 리팩토링 작업도 진행하였습니다.
- class-validator 부분 오류가 자주 나서 이 부분을 신경썼습니다.

[enhancement] post api

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Common/UI/MacroCarouselView.swift
iOS/Macro/Macro/Common/UI/MacroCarouselViewCell.swift
iOS/Macro/Macro/Common/UI/MacroCrouselViewCell.swift

#69 
Crousel View 공통으로 사용할 수 있도록 구현
Crousel View 공통으로 사용할 수 있도록 구현
ViewController에서 적용하는 예시는 아래와 같습니다.
```Swift
import UIKit
class ViewController: UIViewController {
/// Cell 크기와 Cell간의 간격 크기를 넣어주세요
let const = MacroCarouselView.Const(itemSize: CGSize(width: 300, height: 400), itemSpacing: 24.0)
private lazy var carouselView: MacroCarouselView = {
let view = MacroCarouselView(items: /*Data*/, const: const)
view.translatesAutoresizingMaskIntoConstraints = false
return view
}()
override func viewDidLoad() {
super.viewDidLoad()
view.addSubview(carouselView)
NSLayoutConstraint.activate([
carouselView.leftAnchor.constraint(equalTo: view.leftAnchor),
carouselView.rightAnchor.constraint(equalTo: view.rightAnchor),
carouselView.heightAnchor.constraint(equalToConstant: const.itemSize.height), …
```

[feat][#69] Carousel View 작업

---

iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/VIew/LocationInfoViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift

특정 마커를 눌렀을 때, 해당 가게의 정보를 알 수 있어야함
특정 마커를 눌렀을 떄, 해당 가게의 이름, 연락처 등등이 나오는 페이지가 나오도록 구현
#67 
공통 체크 리스트
iOS 체크 리스트

[feat][#67] 경로추천 Segment 의 locationInfo 를 보여주는 기능 구현

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Info.plist
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
iOS/Macro/Macro/Util/LocationManager.swift

- 이슈번호 #80 
LocationManager 백그라운드 모드 설정 완료했습니다. :)
잘 돌아가요.
Close #80
공통 체크 리스트
iOS 체크 리스트

[feat][#80] LocationManager 백그라운드 모드 설정

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Common/UI/MacroCarouselView.swift
iOS/Macro/Macro/Common/UI/MacroCarouselViewCell.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift

#83 WriteView UI 구현
#69 오타 수정 및 PageIndex 삽입
WriteView UI 구현

[feat] WriteView UI 구현

---

server/src/auth/auth.controller.ts
server/src/auth/auth.service.ts
server/src/file/file.controller.ts
server/src/post/post.controller.ts
server/src/post/post.detail.query.dto.ts
server/src/post/post.detail.response.dto.ts
server/src/post/post.pagenation.dto.ts
server/src/post/post.route.validator.ts
server/src/post/post.service.ts
server/src/post/post.write.body.ts
server/src/user/user.profile.update.query.dto.ts
server/src/utils/response.validation.interceptor.ts

- #77 
- Post API 전반 코드를 조금씩 건드리고 Swagger 문서를 상세화했습니다.
- Post API 관련 Validation DTO 수정
- Swagger 문서 상세화
- 여타 API 오류 등 수정
<!-- 
Close #[issueNumber]

[feat] [#77]  Post Api 개선 및 Validation 수정. Swagger 문서 상세화

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Common/Entities/PostFindResponse.swift
iOS/Macro/Macro/Common/Entities/Writer.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostProfileView.swift
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/ViewModel/HomeViewModel.swift
iOS/Macro/Macro/Scene/Home/Network/PostEndPoint.swift

#89 
기존에 목 데이터를 불러오던 것을 서버의 데이터를 불러오도록 변경 필요
서버 데이터를 불러오도록 변경
#89
공통 체크 리스트
iOS 체크 리스트

[feat][#89] 기존에 mock 데이터를 불러오던 것을, 서버의 데이터를 불러오도록 구현

---

iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift

#87 
MyPage의 초기 View 구성
- 수정하는 로직의 함수를 추가로 만들어야할 필요가 있음
- iPhone SE
- iPhone 15 pro
공통 체크 리스트
iOS 체크 리스트

[feat][#87] mypage의 초기 View 구성

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
iOS/Macro/Macro/Common/UI/MacroCarouselView.swift
iOS/Macro/Macro/Common/UI/MacroCarouselViewAddImageCell.swift
iOS/Macro/Macro/Common/UI/MacroCarouselViewCell.swift
iOS/Macro/Macro/Info.plist
iOS/Macro/Macro/Scene/Write/Entities/ImageURLResponse.swift
iOS/Macro/Macro/Scene/Write/Entities/WriteRequestDTO.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift
iOS/Macro/Macro/Scene/Write/Network/ImageUploadEndPoint.swift
iOS/Macro/Macro/Scene/Write/Network/WriteEndPoint.swift
iOS/Macro/Macro/Scene/Write/UseCases/UploadImage.swift

#84 
이미지 업로드 후 URL 받아오기 구현
이미지 업로드 후 URL 받아오기 구현

[feat][#84] 이미지 업로드 후 URL 받아오기 구현

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/App/SceneDelegate.swift
iOS/Macro/Macro/Infrastructure/PersistentStorages/KeyChainManager.swift
iOS/Macro/Macro/Infrastructure/PersistentStorages/TokenManager.swift
iOS/Macro/Macro/Scene/Login/Entities/RefreshTokenResponse.swift
iOS/Macro/Macro/Scene/Login/Network/Model/RefreshTokenEndPoint.swift
iOS/Macro/Macro/Scene/Login/UseCases/RefreshTokenUseCase.swift

- #98 Refresh Token 구현
- SceneDelegate에서 login으로 들어가는 분기에 Refresh Token 추가
#98

[feat] Refresh Token 구현

---

server/src/utils/namemaker.ts
server/tsconfig.json

- #114 
- namemaker 오류를 해결했습니다.
- 이상 동일
close #114

[fix] [#114] namemaker 오류 해결

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Common/TabBar/View/TabBarViewController.swift
iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
iOS/Macro/Macro/Common/UseCases/SearchUseCase.swift
iOS/Macro/Macro/Resource/FollowMock.json
iOS/Macro/Macro/Resource/UserInfoMock.json
iOS/Macro/Macro/Resource/tempJson.json
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/ViewModel/HomeViewModel.swift
iOS/Macro/Macro/Scene/UserInfo/Entities/FollowResponse.swift
iOS/Macro/Macro/Scene/UserInfo/Entities/UserInfo.swift
iOS/Macro/Macro/Scene/UserInfo/Entities/UserInfoResponse.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoHeaderView.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoProfileView.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoViewController.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/ViewModel/UserInfoViewModel.swift
iOS/Macro/Macro/Scene/UserInfo/Network/FollowEndPoint.swift
iOS/Macro/Macro/Scene/UserInfo/Network/UserInfoEndPoint.swift
iOS/Macro/Macro/Scene/UserInfo/UseCases/FollowUseCase.swift

- #96 
- userInfo View관련 작업 입니다. :)
- userInfo View에 관련한 작업을 했습니다.
https://github.com/boostcampwm2023/iOS03-Macro/assets/87685946/e7c66a9e-5349-4125-b668-9d88777d48b5
Close #96 
공통 체크 리스트
iOS 체크 리스트

[feat][#96] userInfoView 작업

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Common/UI/MacroCarouselView.swift
iOS/Macro/Macro/Common/UI/MacroCarouselViewAddImageCell.swift
iOS/Macro/Macro/Common/UI/MacroCarouselViewCell.swift
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
iOS/Macro/Macro/Scene/Read/Entities/ReadPost.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
iOS/Macro/Macro/Scene/Read/Network/ReadEndPoint.swift
iOS/Macro/Macro/Scene/Read/UseCases/ReadPostUseCase.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift

#99 ReadView API 연결 작업
ReadView API 연결 작업
HomeView에서 Cell 클릭 시 ReadView를 호출하고 API 요청 후 값을 가져오도록 수정
Close #99

[feat][#99] ReadView API 연결 작업

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Info.plist
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/IntroductionEditView.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyInfoViewController.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/NameEditView.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift

셀을 눌렀을 때 이동 처리 필요
1. 내 정보 페이지 수정을 눌렀을 때, 다른 View로 이동처리 구현
2. 번들 id 형식에 맞게 변경

[feat][#105] 유저페이지 추가작업

---

server/src/migrations/1701161580726-Migration.ts
server/src/post/post.controller.ts
server/src/post/post.service.ts

- #129 
- 인기 게시글에 대한 구체적 정렬 기준을 마련합니다.
- 조회수 * 0.2 + 좋아요수 * 0.8
Close #129

[improve] 인기 게시글 정렬기준

---

server/src/auth/apple/apple.auth.controller.ts
server/src/auth/auth.controller.ts
server/src/entities/place.entity.ts
server/src/entities/post.content.element.entity.ts
server/src/entities/post.entity.ts
server/src/file/file.controller.ts
server/src/map/map.controller.ts
server/src/map/map.kakao.controller.ts
server/src/map/map.kakao.search.response.dto.ts
server/src/post/place.base.dto.ts
server/src/post/post.controller.ts
server/src/post/post.detail.response.dto.ts
server/src/post/post.module.ts
server/src/post/post.service.ts
server/src/post/post.upload.body.dto.ts
server/src/user/user.controller.ts

- #137 
- place 테이블 추가 및 ping 관련 로직을 추가하였습니다.
- #138 
- swagger 문서를 수정 및 정리하였습니다.
- place 테이블 추가
- place 관련 dto 추가 및 post dto 수정
- place 관련 비즈니스 로직 반영
- place 관련 swagger 설명 추가
- 기타 swagger 설명 정리
Close #137 
Close #138

[add & docs] [#137, #138] ping 정보 추가 및 swagger 문서 정리

---

server/src/entities/post.entity.ts
server/src/migrations/1701250342199-Migration.ts
server/src/post/post.content.element.base.dto.ts
server/src/post/post.controller.ts
server/src/post/post.detail.response.dto.ts
server/src/post/post.service.ts
server/src/post/post.upload.body.dto.ts

- #144 
- pings => pins 용어 변경
- 마이그레이션 파일도 포함됩니다.

[fix] pings => pins

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Common/Entities/PatchResponse.swift
iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
iOS/Macro/Macro/Common/UseCases/PatchUseCase.swift
iOS/Macro/Macro/Infrastructure/PersistentStorages/TokenManager.swift
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
iOS/Macro/Macro/Scene/MyPage/Entities/ConfirmError.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyInfoViewController.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
iOS/Macro/Macro/Scene/MyPage/Network/UpdateUserEndPoint.swift
iOS/Macro/Macro/Scene/MyPage/UseCases/ComfirmUseCase.swift
iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift

mypage 정보 수정 필요
1. Mypage에서 내가 작성한글들을 불러올 수 있게 구현
2. 처음 mypage화면에 진입시 내 정보 가져와서 표시
3. 내 정보를 수정해서 서버에 patch 가능
4. 잘못된 입력을 클라이언트에서 검증. 실패시 alert 표시. 성공시 창이 닫힘
추후에 사진 업로드는 추가해야함.
https://github.com/boostcampwm2023/iOS03-Macro/assets/118811606/1cd01ec2-98ba-4286-9e94-8f3a05770f6f
iOS 체크 리스트

[feat][#143] mypage 수정 작업

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Common/Entities/Coordinate.swift
iOS/Macro/Macro/Common/Entities/Cotent.swift
iOS/Macro/Macro/Common/Entities/Post.swift
iOS/Macro/Macro/Common/UI/MacroCarouselView.swift
iOS/Macro/Macro/Infrastructure/PersistentStorages/ImageSaveManager.swift
iOS/Macro/Macro/Scene/Read/Entities/ReadPost.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
iOS/Macro/Macro/Scene/Route/InterfaceAdapters/ViewModel/RouteViewModel.swift
iOS/Macro/Macro/Scene/Write/Entities/PostUploadResponse.swift
iOS/Macro/Macro/Scene/Write/Entities/WriteRequestDTO.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift
iOS/Macro/Macro/Scene/Write/Network/PostUploadEndPoint.swift
iOS/Macro/Macro/Scene/Write/Network/WriteEndPoint.swift
iOS/Macro/Macro/Scene/Write/UseCases/UploadPost.swift
iOS/MacroNetwork/Sources/MacroNetwork/APIProvider.swift

#83 WriteView CarouselView 수정, PHPhotolibrary -> ImagePicker로 수정
#84 작성한 글 모아서 전송 구현
#99 ReadView CarouselView 수정, DebugPrint 값 수정
#12 JWT Token Email 얻는 코드 추가
#32 Response Body값 출력 코드 추가
WriteView 작업 도중에 필요하거나 다른 부분을 너무 광대하게 건드는 실수를 하였습니다.
RouteView에서 Travel Data를 가져온 후 그 데이터를 전송하는 코드를 구현하였습니다.

[feat] WriteView API 연결

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageHeaderView.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift

- #154
- 배포에 앞서 디자인에 맞춰 세세한 디자인 작업을 하였습니다.
Close #154

[feat][#154] MyPage 디자인 디테일 작업

---

iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift

<!-- 
#83 글 작성에서 생기는 작은 문제점들 개선
- 키보드 내리기 구현
- CarouselView 크기 조정
- 글 작성 후 완료 처리
- 리네임 설정

[enhancement][#83] 글 작성 에러 수정

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyInfoViewController.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
iOS/Macro/Macro/Util/UIViewController+.swift

키보드 코드 수정 필요
키보드 코드를 util 로 변경
my page에서도 사용가능

[chore] 키보드 숨기는 부분 util로 빼고, mypage에서도 사용할 수 있도록 구현

---

server/src/app.module.ts
server/src/sentiment/sentiment.analysis.body.dto.ts
server/src/sentiment/sentiment.analysis.response.dto.ts
server/src/sentiment/sentiment.controller.ts
server/src/sentiment/sentiment.module.ts
server/src/sentiment/sentiment.service.ts

- #178 
- 글의 감정을 분석하는 기능을 추가하였다.
- 현재 글의 내용을 넣으면 감정을 분석해주는 기능이다. 
- 너무 우선순위가 낮은 기능이다.
Close #178

[feat][#178] Clova Sentiment API

---

iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
iOS/Macro/Macro/Scene/Travel/UseCases/RouteRecorder.swift

- #192 
- View Issue 해결 및 불필요한 Print문 제거
- View Issue 해결
- 불필요한 Print문 제거

[feat][#192] View Issue 해결 및 불필요한 Print문 제거

---

iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift

- #194
- 위, 경도 이슈 해결
- 현재 y, x 축을 저장할 때, 반대로 저장하던 이슈를 해결하였습니다.

[feat][#194] 위, 경도 이슈 해결

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Common/UseCases/SearchUseCase.swift
iOS/Macro/Macro/Scene/MyPage/Entities/FollowList.swift
iOS/Macro/Macro/Scene/MyPage/Entities/FollowType.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/FollowResultCell.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/FollowResultCollectionView.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/FollowViewController.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
iOS/Macro/Macro/Scene/MyPage/Network/FollowListEndPoint.swift
iOS/Macro/Macro/Scene/UserInfo/Entities/FollowResponse.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoHeaderView.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoProfileView.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoViewController.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/ViewModel/UserInfoViewModel.swift
iOS/Macro/Macro/Scene/UserInfo/Network/FollowEndPoint.swift
iOS/Macro/Macro/Scene/UserInfo/UseCases/FollowUseCase.swift

팔로우 기능 구현
1. 특정 유저 팔로우 가능
2. 특정 유저 팔로우 취소 가능
3. 내 자신을 팔로우하려고 하면, 버튼은 남아있지만 누를 수는 없음.
4. 마이페이지의 팔로우 목록으로 가면, 나를 팔로우하고있는 사람, 내가 팔로우 하고있는 사람 확인 가능

[feat][#203] 팔로우 기능 구현

---

iOS/Macro/Macro/Common/TabBar/View/TaBarBackgroundLineView.swift
iOS/Macro/Macro/Common/TabBar/View/TabBarViewController.swift

- #205 
- 애니메이션이 navigation 이동시 종료되는 이슈 해결
- 애니메이션이 navigation 이동시 종료되는 이슈를 라이프 사이클에 함수를 넣어 해결했습니다.

[feat][#205] 라이프 사이클에 애니메이션 시작, 종료 함수 추가

---

iOS/Macro/Macro/Info.plist

- #210 
- 수출 규정 관련 문서 관련 Plist 수정
- 재성님께서 도움주신 수출 규정 관련 문서 관련 Plist 수정 부분을 적용합니다.
Close #210

[feat][#210] 수출 규정 관련 문서 관련 Plist 수정

---

iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift

- #212 글 작성 공개 여부 기본 값 public으로 고정
- #212 올리는 이미지 압축하기
- #212 글 작성 완료 버튼 중복 클릭 방지
- 글 작성 공개 여부 기본 값 public으로 고정
- 올리는 이미지 압축하기
- 글 작성 완료 버튼 중복 클릭 방지

[enhancement]

---

iOS/Macro/Macro/Scene/Read/Entities/ReadPost.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift

- #215 ReadView 지도에서 화면 비정상 표기 되던 문제 해결
ReadView Map에서 비정상적인 지형 표기되던 문제 해결
#215

[fix][#215] ReadView Map 비정상 표기 수정

---

iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift

- #220 message Button 제거
- #220 UI Figma에 맞게 수정
- #220 좋아요 기능 연결
ReadView Figma에 맞게 수정
좋아요 기능 API 연결
Message Button 미사용으로 인해 제거
#220

[enhancement][#220] ReadView UI Figma에 맞게 수정

---

server/src/post/post.find.response.dto.ts
server/src/post/post.service.ts

[fix] [#224] post 오류 수정

---

iOS/Macro/Macro/Info.plist
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift

문의하기 기능구현
- #227
- 문의하기 기능을 구현합니다.
-  문의하기 기능을 구현합니다.
https://github.com/boostcampwm2023/iOS03-Macro/assets/87685946/fcd8bd03-79de-4dfb-812e-81ff810a6aec
Close #227
공통 체크 리스트
iOS 체크 리스트

[feat][#227] 문의하기 기능구현

---

iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewCell.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostProfileView.swift
iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/ViewModel/LocationInfoViewModel.swift

1. 프로필 이미지, 메인 이미지에서 자신의 이미지만 나옴.
2. 메인이미지도 없을때 appimage.defaultimage 가 보이게했음

[fix][#213] 컬렉션뷰 문제해결

---

server/package-lock.json
server/package.json
server/src/auth/apple/apple.auth.service.ts
server/src/post/post.service.ts
server/src/utils/logger.interceptor.ts
server/src/utils/utils.module.ts

- #234 
- post/hits, post/search 캐싱

[improve] [#234] Post Hits, Search 캐싱

---

iOS/Macro/Macro/Common/UI/CarouselView/MacroCarouselCollectionView.swift
iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/VIew/LocationInfoViewController.swift

- #237
- 여행 상세보기 layout 디테일 수정
- carousel collctionView inset 수정
-  여행 상세보기 layout 디테일 수정 (안잡혀진 trailing 만 추가했습니다. )
- carousel 고정 inset 45 -> (UIScreen = itemSize) / 2

[enhancement] 여행 상세보기 layout 디테일, carousel collectionView 디테일 

---

iOS/Macro/Macro/Common/UI/AlertView/CustomAlertViewController.swift
iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift

- #239
- 이슈에 대한 작업 한줄 설명
- 이슈에 적은 내용을 한번에 묶어 처리했습니다.
post configure은 차후에 completion 이나 task 를 써 처리하도록 하겠습니다. 배포까지 우선 화이팅
Close #239

[enhancement][#239] 각종 이슈 처리

---

iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift

- #258
- 이미지가 캐시될 경우 불러오지 못하는 이슈 해결
- 이미지가 캐시될 경우 불러오지 못하는 이슈 해결
Close #258

[fix][#258] readView 수정

---

iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
iOS/Macro/Macro/Scene/Travel/Service/LocationManager.swift

travel page bug fix
1. 종료 버튼을 누르면,더 이상 맵에 경로가 그려지지 않도록 구현
2. 앱을 처음 깔았을 때, 내 위치가 표시되지 않던 버그 수정
3. readViewd에서 유저 프로필을 볼 수 없던 버그 수정

[fix][#244] travel page 버그 fix

---

server/src/post/post.cache.repository.ts
server/src/post/post.controller.ts
server/src/post/post.module.ts
server/src/post/post.service.ts
server/src/user/user.profile.simple.response.dto.ts
server/src/utils/keyword.autocomplete.service.ts
server/src/utils/redis/redis.module.ts
server/src/utils/redis/redis.service.ts

- #268 
- 게시글 API 리팩토링
Close #268

[improve] [#268] post refactoring

---

server/src/app.module.ts
server/src/entities/report.entity.ts
server/src/migrations/1702067556528-Migration.ts
server/src/post/post.cache.repository.ts
server/src/post/post.controller.ts
server/src/post/post.module.ts
server/src/post/post.service.ts
server/src/report/report.controller.ts
server/src/report/report.module.ts
server/src/report/report.post.query.dto.ts
server/src/report/report.service.ts
server/src/user/user.profile.simple.response.dto.ts
server/src/utils/keyword.autocomplete.service.ts
server/src/utils/redis/redis.module.ts
server/src/utils/redis/redis.service.ts

- #270
-  collectionView diffabledatasource 이전 코드로 롤백
- 발표까지 사이드 이펙트를 잡는 공수를 다처리하지 못할 것 같아 이전으로 되돌립니다.

[hotfix][#270] collectionView diffabledatasource 이전 코드로 롤백

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro.xcodeproj/xcshareddata/xcschemes/Macro.xcscheme
iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
iOS/Macro/Macro/Scene/Read/Entities/ReportResponse.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
iOS/Macro/Macro/Scene/Read/Network/ReportEndPoint.swift
iOS/Macro/Macro/Scene/Read/UseCases/ReportUseCase.swift
iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIImage+.swift

- #266
- 게시글 신고 기능 추가
- 게시글 신고하기 기능을 추가하고 API 연동 했습니다.
뭐시기 뭐시기 
게시글 삭제도 있어야 할까 싶어요. 일단 월요일 오늘 자정까지 다시 심사 올려보고 반응을 봐야할 것 같아요.
Close #266

[feat][#266] 게시글 신고기능 추가

---

iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteModalViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
iOS/Macro/Macro/Scene/Travel/Service/LocationManager.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoHeaderView.swift

travel page 버그를..전부..수정한듯? (아닐수도있음)
1. 유저팔로우 & 프로필을 볼수없던 버그 수정
2. 한번에 경로기록을 여러번 가능 ( 중지버튼을 누르면 코어데이터에 저장되고, 다시 시작버튼을 눌러서 새로운 기록 가능)
3. 경로 기록에서도 line 색상 수정
4. 경로 기록 중지를 누르면, 이제 map에서 마커들과 기록된 경로가 모두 제거되고, 코어데이터에 기록됨
5. 경로기록 중지를 눌렀을 때, alert로 1번 더 확인
6. 검색 페이지에서 검색했을 때, 2글자 이상 검색할 것을 placeholder로 요구함
Close #244

[fix][#244] travelpage 버그 추가 수정 및 기능 추가

---

iOS/Macro/Macro/Scene/LocationInfo/Entities/RelatedLocation.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteModalViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/SearchResultViewController.swift

travelpage tableview 수정 필요
1. travel page 에서 검색 결과, pin 한 장소 폰트 바꿈
2. 검색한 결과에 주소도 나오록 수정
3. 함께 많이 간 장소가 나오지 않던 버그 수정

[feat] travel page 폰트 수정, locationinfo 버그 수정

---

iOS/Macro/Macro/Common/Entities/Writer.swift
iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/VIew/LocationInfoViewController.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift

[enhancement][#282] 각종 이슈해결

---

server/src/post/post.cache.repository.ts
server/src/post/post.service.ts

- #276 
- multiget 관련 이슈를 해결합니다.
Close #276

[fix] [#276] post multi get

---

iOS/Macro/Macro/Common/UI/EmptyView/DataEmptyView.swift
iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/VIew/LocationInfoViewController.swift
iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/ViewModel/LocationInfoViewModel.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageHeaderView.swift
iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift
iOS/Macro/Macro/Scene/Search/InterfaceAdapters/ViewModel/SearchViewModel.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/SearchResultViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoViewController.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/ViewModel/UserInfoViewModel.swift

- #279]
- 데이터가 없을 때 보여주는 화면 작업 
- UserInfo
- Travel
- Search
- LocationInfo
- action이 없을 경우 버튼이 사라지도록 처리

[feat][#279] Data가 없을 때 데이터가 없음을 보여주는 화면 작업

---

server/src/auth/apple/apple.auth.service.ts
server/src/auth/apple/apple.module.ts
server/src/auth/authentication.dto.ts
server/src/entities/place.entity.ts
server/src/entities/post.entity.ts
server/src/entities/report.entity.ts
server/src/entities/route.entity.ts
server/src/entities/user.entity.ts
server/src/migrations/1702220670805-Migration.ts
server/src/user/user.service.ts

<!-- 
- #278 
- #287 
Close #278 
Close #287

[fix] [#278, #287] user follower

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift

- #291 
- 위치, 사진 이용동의 문구 수정, 로그아웃 추가, 회원탈퇴 로직 수정
- 위치, 사진 이용동의 문구 수정, 로그아웃 추가, 회원탈퇴 로직 수정 했습니다. 마지막까지 화이팅

[enhancement][#291]  위치, 사진 이용동의 문구 수정, 로그아웃 추가, 회원탈퇴 로직 수정

---

iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift

- #289 글 상세페이지에서 이미지와 매핑 된 Pin이 있으면 화면이 이동
- #290 이미지와 Pin 매핑
- #293 핀 한글자씩 보이던 버그 수정
글 작성 시 Pin을 눌러서 이미지와 매핑하고 이를 글 상세 페이지에서 보일 수 있도록 수정
또한 글 작성 시 Pin 한글자씩 보이던 버그 수정
Close #289 
Close #290 
Close #293

[feature] 이미지와 Pin 매핑

---

server/src/post/post.cache.repository.ts
server/src/utils/utils.module.ts

- #298 
- #299 
Close #298 
Close #299

[fix] [#298, #299] 게시글 개수 로딩, typeorm error

---

iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewCell.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
iOS/Macro/Macro/Scene/Read/Entities/ReadPost.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift

- #251 조회수 반영 안되던 문제 해결
Close #251

[fix][#251] 조회수 반영 안되던 문제 해결

---

server/src/auth/apple/apple.auth.service.ts
server/src/auth/auth.module.ts
server/src/auth/blacklist/blacklist.module.ts
server/src/auth/blacklist/user.blacklist.manager.ts
server/src/auth/jwt.authentication.gaurd.ts
server/src/user/user.subscriber.ts
server/src/utils/redis/redis.service.ts

[fix] [#308] 회원 탈퇴 시 토큰 관리

---

iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/ViewModel/LocationInfoViewModel.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
iOS/Macro/Macro/Scene/Travel/Service/LocationManager.swift

위치 권한을 동의하지 않은 사용자에 대한 예외처리 필요
1. 위치권한을 미동의한 사용자에 대해서는 시작버튼, 내위치로 가는 버튼을 누르면 위치 설정을 할 것을 요구
2. 메인스레드가 아닌 곳에서 이미지 변경하던것 변경
3. locationInfo에서 placeID 이전에 직접 지정해서 보여주던것, 실제 ID로 변경
4. 처음에 좌표를 무조건 2개씩 생성하도록 변경하여서, 글작성 실패가 나지 않도록 개선

[fix] 앱 초기 위치 권한에 따른 분기 처리

---

iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyInfoViewController.swift

customAleart 변경
- #310
앱 내 통일성을 주기위해 기존 aleart 에섯 customAleart로 변경하였습니다.

[chore][#310] MyInfo CustomAleart 변경

---

iOS/Macro/Macro.xcodeproj/project.pbxproj

- #314
위치 동의 InfoPlist 수정
Close #314

[feat][#314] edit InfoPlist

---

iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostProfileView.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift

버그리포팅 피드백 적용 필요
1. 다른 곳을 터치하면 키보드가 없어지는 기능 추가
2. read하는 곳에서 마커를 누르면, 해당 Locationinfo 페이지로 넘어가도록 구현
3. 현재 하이라이트 되고 있는 pin은 색깔도 변경되도록 구현

[chore] 버그리포팅 피드백 적용

---

iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoProfileView.swift

- #322
- Introduce Issue 해결
-  Introduce Issue 해결
- guard 문이 있어어 return 되고 있었습니다. 순서를 바꿨어요.
Close #322

[fix][#322] Introduce Issue 해결

---

iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift

네이버지도 최소 zoomLevel 설정
- #326
- 네이버지도 최소 zoomLevel 설정
- 경로가 없을 때 최소 줌레벨을 설정합니다.
Close #326

[feat][#326] 네이버지도 최소 zoomLevel 설정

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/App/SceneDelegate.swift
iOS/Macro/Macro/Infrastructure/PersistentStorages/TokenManager.swift
iOS/Macro/Macro/Scene/Login/InterfaceAdapters/View/LoginViewController.swift
iOS/Macro/Macro/Scene/UserAgreement/InterfaceAdapters/Entities/UserAgreementModel.swift
iOS/Macro/Macro/Scene/UserAgreement/InterfaceAdapters/View/UserAgreementHeaderView.swift
iOS/Macro/Macro/Scene/UserAgreement/InterfaceAdapters/View/UserAgreementTapView.swift
iOS/Macro/Macro/Scene/UserAgreement/InterfaceAdapters/View/UserAgreementViewController.swift
iOS/Macro/Macro/Scene/UserAgreement/InterfaceAdapters/ViewModel/UserAgreementViewModel.swift
iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIColor+.swift
iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIImage+.swift

[feat][#329] 유저 정보 동의 화면 구현

---

README.md

비디오 영상 최신화 필요
README.md의 비디오 최산화

[chore] 앱 시연 영상 수정

---

server/src/auth/apple/apple.auth.service.ts
server/src/auth/apple/apple.client.auth.response.dto.ts
server/src/report/report.controller.ts
server/src/report/report.user.query.dto.ts

- #337
- 애플로그인 시에 회원가입 여부를 반환합니다.

[fix] [#337] 회원가입 여부 
