boostcampwm2023/iOS03-TravelShare

server/.eslintrc.js
server/src/map/map.kakao.controller.ts
server/src/map/map.kakao.search.response.dto.ts
server/src/map/map.kakao.service.ts
server/src/map/map.module.ts

- #25 
- 기존 네이버 검색은 5개밖에 나오지 않아 카카오로 바꿨다.
- https://jijihuny.store/map/v2/searchByAccuracy?keyword={keyword} 
- https://jijihuny.store/map/v2/searchByDistance?keyword={keyword}&x={x}&y={y} 
- ex) http://jijihuny.store/map/v2/searchByDistance?keyword=고기=126.7815676147119&y=37.65111857134181
- 이론상 1350개까지 될 것 같은데 지금은 15개만 나온다.
- 수정 가능할 것 같다. <b>추후 수정사항</b>
Close #25 
공통 체크 리스트

[Improve] #25 naver api to kakao api

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Scene/Travel/Entities/SavedRoute.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteTableViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/SearchResultViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
iOS/Macro/Macro/Scene/Travel/UseCases/LocationSearcher.swift
iOS/Macro/Macro/Scene/Travel/UseCases/PinnedPlaceManager.swift
iOS/Macro/Macro/Scene/Travel/UseCases/RouteRecorder.swift
iOS/MacroDesignSystem/Sources/Network/APIProvider.swift

여행 경로를 기록하는 페이지에서, 추가적인 구현이 필요
travel을 하는 페이지의 상세 기능 구현
1. pin 처리 할 시, pin.fill과 pin으로 표시
2. 처음 앱 실행 시 현재 위치로 조정됨
3. 새로 pin 처리할 시, 해당 장소로 카메라가 이동됨
4. Pin 처리할 시, 해당 좌표에 숫자가 표시 됨
5. 추가, 삭제, 위치 변경 등을 해도 마커들이 해당 작업에 맞게 수정 됨
핀 처리한 장소, 내 실제 경로는 ViewModel에서 관리하고 있으나, 그것들을 가공처리하는 것은 UseCase에서 이루어 지는 것이 고민입니다.
결국 함수형 프로그래밍을 하는 것같은 느낌이 들었는데, 원본 배열,  추가할 element를 넘겨주어서 그것을 추가한 것을 리턴 받는 형식인데, 
이게 Clean Architecture 에 맞는 건가 .. ? 하는 생각이 들었던 것 같습니다.
https://github.com/boostcampwm2023/iOS03-Macro/assets/118811606/6c90c8c9-0f2c-47f8-857e-7702502fb220
https://github.com/boostcampwm2023/iOS03-Macro/assets/118811606/49bd36f6-f5e4-47c6-97dc-dc2628d6034e
https://github.com/boostcampwm2023/iOS03-Macro/assets/118811606/53766837-0cf8-49e6-b10d-6ca1434c3ada
공통 체크 리스트
iOS 체크 리스트

[feat][#11] travel page의 추가적인 기능 구현

---

server/src/app.controller.ts
server/src/map/map.kakao.controller.ts
server/src/map/map.kakao.search.accuracy.query.dto.ts
server/src/map/map.kakao.search.distance.query.dto.ts
server/src/map/map.kakao.service.ts

- #25 
- 기존에는 pagenum이 1로만 지정되어 있었는데, pagenum을 parameter로 넣을 수 있게 바꿔줬다.
- ex) jijihuny.store/map/v2/searchByAccuracy?keyword="부평 라멘"&pagenum=2
- ex) jijihuny.store/map/v2/searchByDistance?keyword=라멘&pagenum=2&x=126.7815676147119&y=37.65111857134181
- 이론상 1350개라고 했는데 문서랑 실제 허용 범위가 달라서 해보니 실제로는 45개였다.
- pagenum은 1,2,3만 가능하다. 그 이후부터는 3과 같은 값들이 출력됨.
Close #25 
공통 체크 리스트

[Improve][#25] kakao search 15 items to 45items

---

server/src/auth/apple/apple.auth.controller.ts
server/src/auth/apple/apple.auth.service.ts
server/src/auth/apple/apple.client.auth.response.dto.ts
server/src/auth/auth.basic.auth.response.dto.ts
server/src/auth/auth.basic.signin.body.dto.ts
server/src/auth/auth.basic.signup.body.dto.ts
server/src/auth/auth.controller.ts
server/src/auth/auth.module.ts
server/src/auth/auth.service.ts
server/src/user/user.controller.ts
server/src/user/user.delete.body.dto.ts
server/src/user/user.service.ts
server/src/user/user.signin.response.dto.ts

- #12 
- 로그인 로직 플로우를 유저 영역에서 분리하여 별도의 auth 영역으로 분리하였습니다.
- access token을 갱신하기 위한 api를 추가하였습니다.
- 원래 유저 인증과 관련한 기본 로직은 User api와 강하게 결합되어 있었습니다.
```
./src/user
├── user.controller.ts
├── user.delete.body.dto.ts
├── user.follow.query.dto.ts
├── user.module.ts
├── user.profile.query.dto.ts
├── user.profile.response.dto.ts
├── user.profile.simple.response.dto.ts
├── user.profile.update.query.dto.ts
├── user.service.ts
├── user.signin.body.dto.ts
├── user.signin.response.dto.ts
└── user.signup.body.dto.ts
```
```ts
@ApiTags('User')
@Controller('user')
export class UserController {
constructor(private readonly userService: UserService) {}
@ApiOperation({ description: '회원가입' })
@ApiResponse({ type: UserSigninResponse })
@Public()
@Post('signup')
async signup(@Body() user: UserSignupBody) { …
```

[feat] [#12] 인증 로직 분리 User => Auth, Access Token refresh api 구현

---

iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/PostProfileView.swift

유저가 작성한 글에서, 유저의 이미지가 보이지 않던 버그 수정필요
유저가 작성한 글에서 유저의 이미지가 보이도록 버그 수정

[fix][#50] 유저 이미지 정보가 보이지 않던 버그 수정

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Common/CommonProtocol/PostCollectionViewProtocol.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewCell.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostProfileView.swift
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/ViewModel/HomeViewModel.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoViewController.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/ViewModel/UserInfoViewModel.swift

- #86 
- 재활용이 많은 PostCollectionView를 Common UI 로 빼왔습니다. :)
- 재활용이 많은 PostCollectionView를 Common UI 로 빼왔습니다. 
- PostCollectionViewProtocol을 만들고 Generic 타입으로 받아와 사용합니다.
reusable 하지만 좋은 코드는 아닌 것 같아요. 이해도 제대로 안되었고, Generic으로 받으니 objc 코드 사용이 불가해서 Gesture 관련 함수를 따로 빼내지 못했어요. static을 사용하지 못해 enum으로 Metrics를 만들어 사용하던 규칙을 지킬 수 없었습니다. cell Identifiler 도 마찬가지입니다.
다른 좋은 방법이 분명 있을 테니 차후 수정이 필요합니다.
https://github.com/boostcampwm2023/iOS03-Macro/assets/87685946/9e746bd7-1339-4941-86cd-dcf2faaad454
#86 
공통 체크 리스트
iOS 체크 리스트

[enhancement] PostCollectionView, Common UI 로 활용 가능하도록 수정

---

iOS/Macro/Macro/CoreData/Macro.xcdatamodeld/Model.xcdatamodel/contents
iOS/Macro/Macro/Scene/Travel/Entities/TravelInfo.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
iOS/Macro/Macro/Util/CoreData/CoreDataManager.swift

- #119 
- 코어데이터를 기획에 맞게 수정합니다.
- 시작, 종료, Sequence, 여행id, 여행Route, PinnedRoute 를 담습니다.
StartAt
코어데이터에 파라미터 보낼 때 5개 이하로 넣으라고 되어 있는 데, 6개라서 린트에 걸려요.
Close #119

[feat][#119] CoreData Table Attribute 변경, 로직 변경

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Common/CommonProtocol/PostCollectionViewProtocol.swift
iOS/Macro/Macro/Common/Entities/ProfileGetResponse.swift
iOS/Macro/Macro/Common/Entities/UserProfile.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewCell.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostProfileView.swift
iOS/Macro/Macro/Common/UseCases/SearchUseCase.swift
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/ViewModel/HomeViewModel.swift
iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/VIew/LocationInfoViewController.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift
iOS/Macro/Macro/Scene/Search/InterfaceAdapters/ViewModel/SearchViewModel.swift
iOS/Macro/Macro/Scene/Search/Network/PostFindEndPoint.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoHeaderView.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoProfileView.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoViewController.swift
iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/ViewModel/UserInfoViewModel.swift
iOS/Macro/Macro/Scene/UserInfo/Network/PostSearchEndPoint.swift

구현된 API 에 대해서 Mock 대신 연결 필요
1. Search page에서 글 제목 기준으로 검색 가능
2. Home page에서 유저 셀을 누르면, 해당 유저가 작성한 게시글, 해당 유저의 실제 정보 확인 가능
3. loacationInfo page의 UI 피그마에 맞게 작업
https://github.com/boostcampwm2023/iOS03-Macro/assets/118811606/62f3829d-55a7-49bf-88b4-e4033e05e3b1

[feat] home, searchpage api 연결

---

server/src/app.module.ts
server/src/config/app.config.module.ts
server/src/config/config.manager.module.ts
server/src/config/config.manager.options.factory.ts
server/src/config/config.manager.register.options.ts
server/src/logger/logger.module.ts
server/src/logger/ncp.elsa.logger.config.factory.ts
server/src/sentiment/sentiment.analysis.config.dto.ts
server/src/sentiment/sentiment.analysis.query.dto.ts
server/src/sentiment/sentiment.analysis.request.dto.ts
server/src/sentiment/sentiment.controller.ts
server/src/sentiment/sentiment.module.ts
server/src/sentiment/sentiment.service.ts
server/src/user/user.followees.query.dto.ts
server/src/user/user.followees.response.dto.ts
server/src/user/user.followers.query.dto.ts
server/src/user/user.followers.response.dto.ts

- #180 
- ConfigModule을 리팩토링하여 모듈 간 설정 파일에 대한 관심사를 분리하고 타입안정성을 확보합니다.
기존엔 설정 파일에 대한 의존성이 모두에게 동일하여
```ts
@Injectable()
export class SomeService {
constructor(
configService: ConfigService
) {}
async doSomething() {
...
this.configService.get('some.config.options')
...
}
```
와 같이 ConfigService를 주입받아야만 했습니다.
이는 타입스크립트의 타입 안정성을 유지하지 못하고,
또 적절한 Config경로를 매번 작성해주어야만 하는 상황입니다.
이제
```ts
export class SomeConfig {
...
}
@Module({
imports: [ ConfigManagerModule.registerAs({ schema: SomeConfig, path: 'path' })]
})
export class SomeModule {}
@Injectable()
export class SomeService {
constructor(someConfig: SomeConfig) {}
}
```
와 같이 각 모듈마다 Config에 대한 스키마로 관심사를 좁히고 타입 안정성을 확보할 수 있게 되었습니다.
Close #180

[improve] [#180] ConfigModule 리팩토링과 타입 안정성 확보

---

iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewModel.swift
iOS/Macro/Macro/Common/UseCases/SearchUseCase.swift
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/ViewModel/HomeViewModel.swift
iOS/Macro/Macro/Scene/Home/Network/PostEndPoint.swift

- 이슈번호 #196
- 게시물을 추가적으로 불러오는 로직과 재호출하는 기능을 구현합니다.
- 게시물을 추가적으로 불러오는 로직과 재호출하는 기능을 구현합니다.
코어데이터 엔터티를 수정하고, 게시물을 쓰는 기능을 제대로 다시 구현하지 않아서 게시물 수가 적습니다. 이 부분만 구현하면 실 테스트가 가능할 것 같습니다.
Close #196

[feat][#196] post refresh, post load 구현

---

iOS/Macro/Macro/Infrastructure/PersistentStorages/ImageSaveManager.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift

<!-- 
- #165 이미지 없으면 글 작성 안되던 문제 해결
기존에 ImageSaveManager의 convertImageDataToImageURL 메소드에서 url 배열을 반복문으로 이미지를 보내고 response를 받은 후 completion을 호출 했습니다. 하지만 배열이 비어있으면 반복문이 호출 되지 않으면서 completion이 호출되지 않는 문제가 발생했습니다.
이를 해결하기 위해 guard문을 만들어서 넣었지만 store하는 과정에서 Race Condition 문제가 생겨서 cancellables를 입력받는 것이 아닌 직접 만들어서 넣어주는 식으로 수정했습니다.
#165

[fix][#165] Image 없으면 글 작성 안되는 문제 해결

---

iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift

- #230 이미지 업로드 및 Read가 순차적으로 될 수 있도록 수정
원인 분석
기존의 글 작성 로직은 아래와 같았다.
Submit 버튼 클릭
Image Data 타입으로 변환
각 이미지를 Object Storage에 전송 후 URL 받는 순서대로 저장
Image URL 배열 순서대로 Content로 변환 후 Post 전송
위 과정 중 3번에서 문제가 발생을 했다.
비동기적으로 Data를 보내고 받은 데이터 부터 배열에 추가해주기 때문에
Data를 보내는 순서대로 처리가 되는 것이 아니라 받는 순서대로 데이터가 쌓여있다.
이를 데이터를 보내는 순서와 맞게 데이터를 받는 방법을 고민해야 한다.
문제 해결 과정
index를 부여했습니다.
기존에는 빈 배열을 만들고 거기에 append 시켜주고 그것이 Image Data 배열과 크기가 같을 때 반환하는 방식으로 진행을 했습니다.
방식을 조금 바꿔서 Data 양만큼의 빈 값을 가진 배열을 만들고 거기에 넣어주는 방식을 채택했습니다.
지금은 배열 크기를 새로 만들어서 인덱스에 넣는 방식으로 하는데 이것이 자연스럽지 못하다는 느낌을 받았습니다.
좀 더 나은 개선 방법이 있다면 의견 주시면 좋을 것 같습니다.
| Before | After |
| -------- | -------- |
|  ![image](https://github.com/boostcampwm2023/iOS03-Macro/assets/37203016/f5dc3166-9ede-49fc-8289-24045ccfa504) | …

[fix][#230] Image Upload 및 Read 순차적으로 될 수 있도록 수정

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/App/SceneDelegate.swift
iOS/Macro/Macro/Common/Entities/CustomAlert/AddAction.swift
iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
iOS/Macro/Macro/Common/UI/AlertView/CustomAlertViewController.swift
iOS/Macro/Macro/Scene/Login/InterfaceAdapters/View/LoginViewController.swift
iOS/Macro/Macro/Scene/MyPage/Entities/AppleRevokeResponse.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController+AuthenticationServices.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
iOS/Macro/Macro/Scene/MyPage/Network/RevokeEndPoint.swift
iOS/Macro/Macro/Scene/MyPage/UseCases/RevokeUseCase.swift
iOS/Macro/Macro/Util/AlertBuilder.swift

- #229
- 회원 탈퇴를 구현합니다.
- 회원탈퇴 로직 구현
- 커스텀 alert 구현
지금 로그아웃만 되고 회원 탈퇴가 되지 않고 있습니다.
분명 요구사항대로 authorizationCode, identityToken 둘 다 보내고 있는 것 같은데요 ㅠㅠㅠ..
차후 의논해서 수정해야 합니다.
Close #229

[feat][#229] 회원 탈퇴 구현

---

iOS/Macro/Macro/App/SceneDelegate.swift
iOS/Macro/Macro/Infrastructure/PersistentStorages/TokenManager.swift

#255 Refresh 실패 시 로그인 화면으로 넘어가도록 설정
기존 로직에서 Login화면과 메인 화면을 분기 처리하는 기준은 accessToken의 기한이 만료가 되었는가 였습니다.
그래서 이것을 RefreshToken으로 한번 더 분기 처리해서 안전하게 처리할 수 있도록 수정하고자 했습니다.

[enhancement][#255] Refresh 실패 시 로그인 화면으로 넘어가도록 설정

---

iOS/Macro/Macro.xcodeproj/project.pbxproj
iOS/Macro/Macro/Common/TabBar/Model/TabComponent.swift
iOS/Macro/Macro/Common/TabBar/Model/TabbarType.swift
iOS/Macro/Macro/Common/TabBar/View/TabBarCenterView.swift
iOS/Macro/Macro/Common/TabBar/View/TabBarViewController.swift
iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostProfileView.swift
iOS/Macro/Macro/Scene/Route/InterfaceAdapters/View/RouteViewController.swift
iOS/Macro/Macro/Scene/Route/InterfaceAdapters/ViewModel/RouteViewModel.swift
iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift
iOS/Macro/Macro/Scene/Search/InterfaceAdapters/ViewModel/SearchViewModel.swift

- #272
- 여행 경로가 없을 때, 여행페이지로 이동하는 UI, 로직, profile Image radius 오류 수정
- profile Image radius 가 bounds가 잡히기 전에 radius를 줘서 변하지 않는 이슈가 있어 해결했어요.
- 피드백 대로 여행 루트가 없을 때, 여행하기로 바로 갈 수 있도록 했습니다.
- 
뷰컨이 자기 자신의 타입을 알고 있는데, 나훈님과 얘기하면서 자기 타입을 들고 있는 것이 좋지 않은 걸 알았어요. 차후 수정이 필요합니다. :)
아직 뷰를 미쳐 다 그리지 못해 빨간 화면으로만 띄워주고 있어요. 주말까지 마무리하겠습니다. 👍 
Close #272

[feat][#272] 여행 경로가 없을 때, 여행페이지로 이동하는 UI, 로직, profile Image radius 오류 수정

---

iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewCell.swift
iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift

#251 상세 페이지의 변경 내용을 CollectionView에 반영
Subject를 생성 후 HomeViewController에서 연결해줬습니다.
해당 View까지의 Depth가 있어서
이를 연결하기 위해서는 너무 많은 Subject가 연결되는 느낌이라 이 부분이 조금 걱정됩니다.
Close #251

[enhancement][#251] 상세 페이지의 변경 내용을 CollectionView에 반영

---

iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift

회원탈퇴 관련 로직 수정 및 불필요한 print 삭제
- #303
- 회원탈퇴를 해도 제대로 안되던 이슈가 있었습니다.
- 관련해서 J120 지훈님과 해결했습니다.
Close  #303

[chore][#303] 회원탈퇴 관련 로직 수정 및 불필요한 print 삭제

---

iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift

- #316 매핑안된 이미지가 스크롤 되면 기존에 매핑 지우기
- 매핑안된 이미지가 스크롤 되면 기존에 매핑 지우기

[fix][#316] 매핑안된 이미지가 스크롤 되면 기존에 매핑 지우기

---

iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift

- #303 
기존 회원탈퇴 로직 수정 과정에서 KeyChain, CoreData 삭제하는 부분이 없어져서 다시 복구했습니다.

[fix][#303] KeyChain, CoreData 삭제 코드 복구

---

iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift

[fix] main page에서만 조회수, 좋아요가 반영되던 버그 수정
컬렉션뷰의 셀 하나만 다시 리로드했습니다.

[fix] main page에서만 조회수, 좋아요가 반영되던 버그 수정

---

iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift

코어데이터 컬렉션뷰 재사용 문제 해결 필요
1. 코어데이터 컬렉션뷰 재사용 문제 해결
2. 경로 기록 좌표 개수 맥시멈 10000개로 지정. 그 이상 넘어가면 기록 강제 중지.
3. 만약 5초전 내 좌표와 현재 좌표가 일치하면, 그 좌표는 추가시켜주지 않도록 로직 추가

[fix] 코어데이터 컬렉션뷰 재사용 문제 해결, 경로 기록 관련 개선
